foldersTree = gFld("<b>wtl-doc</b>", "", "")
     insDoc(foldersTree, gLnk("Doxygen generated documentation for the WTL classes", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("atlapp.h", "", "atlapp_8h.html"))
       insDoc(aux1, gLnk("atlcrack.h", "", "atlcrack_8h.html"))
       insDoc(aux1, gLnk("atlctrls.h", "", "atlctrls_8h.html"))
       insDoc(aux1, gLnk("atlctrlw.h", "", "atlctrlw_8h.html"))
       insDoc(aux1, gLnk("atlctrlx.h", "", "atlctrlx_8h.html"))
       insDoc(aux1, gLnk("atlddx.h", "", "atlddx_8h.html"))
       insDoc(aux1, gLnk("atldlgs.h", "", "atldlgs_8h.html"))
       insDoc(aux1, gLnk("atlframe.h", "", "atlframe_8h.html"))
       insDoc(aux1, gLnk("atlgdi.h", "", "atlgdi_8h.html"))
       insDoc(aux1, gLnk("atlmisc.h", "", "atlmisc_8h.html"))
       insDoc(aux1, gLnk("atlprint.h", "", "atlprint_8h.html"))
       insDoc(aux1, gLnk("atlres.h", "", "atlres_8h.html"))
       insDoc(aux1, gLnk("atlscrl.h", "", "atlscrl_8h.html"))
       insDoc(aux1, gLnk("atlsplit.h", "", "atlsplit_8h.html"))
       insDoc(aux1, gLnk("atltheme.h", "", "atltheme_8h.html"))
       insDoc(aux1, gLnk("atluser.h", "", "atluser_8h.html"))
       insDoc(aux1, gLnk("extra-documentation", "", "extra-documentation.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("WTL::_AtlFrameWnd_CmdBarPopupMenu", "", "structWTL_1_1__AtlFrameWnd__CmdBarPopupMenu.html"))
       insDoc(aux1, gLnk("WTL::_printer_info", "", "classWTL_1_1__printer__info.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 1 >", "", "classWTL_1_1__printer__info_3_011_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 2 >", "", "classWTL_1_1__printer__info_3_012_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 3 >", "", "classWTL_1_1__printer__info_3_013_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 4 >", "", "classWTL_1_1__printer__info_3_014_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 5 >", "", "classWTL_1_1__printer__info_3_015_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 6 >", "", "classWTL_1_1__printer__info_3_016_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 7 >", "", "classWTL_1_1__printer__info_3_017_01_4.html"))
       insDoc(aux1, gLnk("WTL::_U_MENUorID", "", "classWTL_1_1__U__MENUorID.html"))
       insDoc(aux1, gLnk("WTL::_U_RECT", "", "classWTL_1_1__U__RECT.html"))
       insDoc(aux1, gLnk("WTL::_U_STRINGorID", "", "classWTL_1_1__U__STRINGorID.html"))
       insDoc(aux1, gLnk("WTL::CAnimateCtrlT", "", "classWTL_1_1CAnimateCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CAppModule", "", "classWTL_1_1CAppModule.html"))
       insDoc(aux1, gLnk("WTL::CAppModule::_ATL_EMPTY_DLGTEMPLATE", "", "structWTL_1_1CAppModule_1_1__ATL__EMPTY__DLGTEMPLATE.html"))
       insDoc(aux1, gLnk("WTL::CAxPropertyPage", "", "classWTL_1_1CAxPropertyPage.html"))
       insDoc(aux1, gLnk("WTL::CAxPropertyPageImpl", "", "classWTL_1_1CAxPropertyPageImpl.html"))
       insDoc(aux1, gLnk("WTL::CBitmapButton", "", "classWTL_1_1CBitmapButton.html"))
       insDoc(aux1, gLnk("WTL::CBitmapButtonImpl", "", "classWTL_1_1CBitmapButtonImpl.html"))
       insDoc(aux1, gLnk("WTL::CBitmapT", "", "classWTL_1_1CBitmapT.html"))
       insDoc(aux1, gLnk("WTL::CBrushT", "", "classWTL_1_1CBrushT.html"))
       insDoc(aux1, gLnk("WTL::CButtonT", "", "classWTL_1_1CButtonT.html"))
       insDoc(aux1, gLnk("WTL::CCheckListViewCtrl", "", "classWTL_1_1CCheckListViewCtrl.html"))
       insDoc(aux1, gLnk("WTL::CCheckListViewCtrlImpl", "", "classWTL_1_1CCheckListViewCtrlImpl.html"))
       insDoc(aux1, gLnk("WTL::CCheckListViewCtrlImplTraits", "", "classWTL_1_1CCheckListViewCtrlImplTraits.html"))
       insDoc(aux1, gLnk("WTL::CClientDC", "", "classWTL_1_1CClientDC.html"))
       insDoc(aux1, gLnk("WTL::CColorDialog", "", "classWTL_1_1CColorDialog.html"))
       insDoc(aux1, gLnk("WTL::CColorDialogImpl", "", "classWTL_1_1CColorDialogImpl.html"))
       insDoc(aux1, gLnk("WTL::CComboBoxExT", "", "classWTL_1_1CComboBoxExT.html"))
       insDoc(aux1, gLnk("WTL::CComboBoxT", "", "classWTL_1_1CComboBoxT.html"))
       insDoc(aux1, gLnk("WTL::CCommandBarCtrl", "", "classWTL_1_1CCommandBarCtrl.html"))
       insDoc(aux1, gLnk("WTL::CCommandBarCtrlBase", "", "classWTL_1_1CCommandBarCtrlBase.html"))
       insDoc(aux1, gLnk("WTL::CCommandBarCtrlBase::_MsgHookData", "", "structWTL_1_1CCommandBarCtrlBase_1_1__MsgHookData.html"))
       insDoc(aux1, gLnk("CCommandBarCtrlImpl", "", "classCCommandBarCtrlImpl.html"))
       insDoc(aux1, gLnk("WTL::CCommonDialogImplBase", "", "classWTL_1_1CCommonDialogImplBase.html"))
       insDoc(aux1, gLnk("WTL::CCustomDraw", "", "classWTL_1_1CCustomDraw.html"))
       insDoc(aux1, gLnk("WTL::CDateTimePickerCtrlT", "", "classWTL_1_1CDateTimePickerCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CDCT", "", "classWTL_1_1CDCT.html"))
       insDoc(aux1, gLnk("WTL::CDevModeT", "", "classWTL_1_1CDevModeT.html"))
       insDoc(aux1, gLnk("CDialogImplBase", "", "classCDialogImplBase.html"))
       insDoc(aux1, gLnk("CDialogImplBaseT", "", "classCDialogImplBaseT.html"))
       insDoc(aux1, gLnk("WTL::CDialogResize", "", "classWTL_1_1CDialogResize.html"))
       insDoc(aux1, gLnk("WTL::CDialogResize::_AtlDlgResizeData", "", "structWTL_1_1CDialogResize_1_1__AtlDlgResizeData.html"))
       insDoc(aux1, gLnk("WTL::CDialogResize::_AtlDlgResizeMap", "", "structWTL_1_1CDialogResize_1_1__AtlDlgResizeMap.html"))
       insDoc(aux1, gLnk("WTL::CDragListBoxT", "", "classWTL_1_1CDragListBoxT.html"))
       insDoc(aux1, gLnk("WTL::CDragListNotifyImpl", "", "classWTL_1_1CDragListNotifyImpl.html"))
       insDoc(aux1, gLnk("WTL::CEditCommands", "", "classWTL_1_1CEditCommands.html"))
       insDoc(aux1, gLnk("WTL::CEditT", "", "classWTL_1_1CEditT.html"))
       insDoc(aux1, gLnk("WTL::CEnhMetaFileDC", "", "classWTL_1_1CEnhMetaFileDC.html"))
       insDoc(aux1, gLnk("WTL::CEnhMetaFileInfo", "", "classWTL_1_1CEnhMetaFileInfo.html"))
       insDoc(aux1, gLnk("WTL::CEnhMetaFileT", "", "classWTL_1_1CEnhMetaFileT.html"))
       insDoc(aux1, gLnk("WTL::CFileDialog", "", "classWTL_1_1CFileDialog.html"))
       insDoc(aux1, gLnk("WTL::CFileDialogImpl", "", "classWTL_1_1CFileDialogImpl.html"))
       insDoc(aux1, gLnk("WTL::CFindFile", "", "classWTL_1_1CFindFile.html"))
       insDoc(aux1, gLnk("WTL::CFindReplaceDialog", "", "classWTL_1_1CFindReplaceDialog.html"))
       insDoc(aux1, gLnk("WTL::CFindReplaceDialogImpl", "", "classWTL_1_1CFindReplaceDialogImpl.html"))
       insDoc(aux1, gLnk("WTL::CFlatScrollBarImpl", "", "classWTL_1_1CFlatScrollBarImpl.html"))
       insDoc(aux1, gLnk("WTL::CFlatScrollBarT", "", "classWTL_1_1CFlatScrollBarT.html"))
       insDoc(aux1, gLnk("WTL::CFolderDialog", "", "classWTL_1_1CFolderDialog.html"))
       insDoc(aux1, gLnk("WTL::CFolderDialogImpl", "", "classWTL_1_1CFolderDialogImpl.html"))
       insDoc(aux1, gLnk("WTL::CFontDialog", "", "classWTL_1_1CFontDialog.html"))
       insDoc(aux1, gLnk("WTL::CFontDialogImpl", "", "classWTL_1_1CFontDialogImpl.html"))
       insDoc(aux1, gLnk("WTL::CFontT", "", "classWTL_1_1CFontT.html"))
       insDoc(aux1, gLnk("WTL::CFrameWindowImpl", "", "classWTL_1_1CFrameWindowImpl.html"))
       insDoc(aux1, gLnk("WTL::CFrameWindowImplBase", "", "classWTL_1_1CFrameWindowImplBase.html"))
       insDoc(aux1, gLnk("WTL::CFrameWindowImplBase::_AtlToolBarData", "", "structWTL_1_1CFrameWindowImplBase_1_1__AtlToolBarData.html"))
       insDoc(aux1, gLnk("WTL::CFrameWindowImplBase::_ChevronMenuInfo", "", "structWTL_1_1CFrameWindowImplBase_1_1__ChevronMenuInfo.html"))
       insDoc(aux1, gLnk("WTL::CFrameWndClassInfo", "", "classWTL_1_1CFrameWndClassInfo.html"))
       insDoc(aux1, gLnk("WTL::CHeaderCtrlT", "", "classWTL_1_1CHeaderCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CHotKeyCtrlT", "", "classWTL_1_1CHotKeyCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CHyperLink", "", "classWTL_1_1CHyperLink.html"))
       insDoc(aux1, gLnk("WTL::CHyperLinkImpl", "", "classWTL_1_1CHyperLinkImpl.html"))
       insDoc(aux1, gLnk("WTL::CIdleHandler", "", "classWTL_1_1CIdleHandler.html"))
       insDoc(aux1, gLnk("WTL::CImageList", "", "classWTL_1_1CImageList.html"))
       insDoc(aux1, gLnk("WTL::CIPAddressCtrlT", "", "classWTL_1_1CIPAddressCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CLinkCtrlT", "", "classWTL_1_1CLinkCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CListBoxT", "", "classWTL_1_1CListBoxT.html"))
       insDoc(aux1, gLnk("WTL::CListViewCtrlT", "", "classWTL_1_1CListViewCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CMapScrollImpl", "", "classWTL_1_1CMapScrollImpl.html"))
       insDoc(aux1, gLnk("WTL::CMapScrollWindowImpl", "", "classWTL_1_1CMapScrollWindowImpl.html"))
       insDoc(aux1, gLnk("WTL::CMDIChildWindowImpl", "", "classWTL_1_1CMDIChildWindowImpl.html"))
       insDoc(aux1, gLnk("WTL::CMDICommandBarCtrl", "", "classWTL_1_1CMDICommandBarCtrl.html"))
       insDoc(aux1, gLnk("WTL::CMDICommandBarCtrlImpl", "", "classWTL_1_1CMDICommandBarCtrlImpl.html"))
       insDoc(aux1, gLnk("WTL::CMDIFrameWindowImpl", "", "classWTL_1_1CMDIFrameWindowImpl.html"))
       insDoc(aux1, gLnk("WTL::CMDIWindow", "", "classWTL_1_1CMDIWindow.html"))
       insDoc(aux1, gLnk("WTL::CMenuItemInfo", "", "classWTL_1_1CMenuItemInfo.html"))
       insDoc(aux1, gLnk("WTL::CMenuT", "", "classWTL_1_1CMenuT.html"))
       insDoc(aux1, gLnk("WTL::CMessageFilter", "", "classWTL_1_1CMessageFilter.html"))
       insDoc(aux1, gLnk("WTL::CMessageLoop", "", "classWTL_1_1CMessageLoop.html"))
       insDoc(aux1, gLnk("CMessageMap", "", "classCMessageMap.html"))
       insDoc(aux1, gLnk("WTL::CMonthCalendarCtrlT", "", "classWTL_1_1CMonthCalendarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CMultiPaneStatusBarCtrl", "", "classWTL_1_1CMultiPaneStatusBarCtrl.html"))
       insDoc(aux1, gLnk("WTL::CMultiPaneStatusBarCtrlImpl", "", "classWTL_1_1CMultiPaneStatusBarCtrlImpl.html"))
       insDoc(aux1, gLnk("WTL::COwnerDraw", "", "classWTL_1_1COwnerDraw.html"))
       insDoc(aux1, gLnk("WTL::CPagerCtrlT", "", "classWTL_1_1CPagerCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CPageSetupDialog", "", "classWTL_1_1CPageSetupDialog.html"))
       insDoc(aux1, gLnk("WTL::CPageSetupDialogImpl", "", "classWTL_1_1CPageSetupDialogImpl.html"))
       insDoc(aux1, gLnk("WTL::CPaintDC", "", "classWTL_1_1CPaintDC.html"))
       insDoc(aux1, gLnk("WTL::CPaletteT", "", "classWTL_1_1CPaletteT.html"))
       insDoc(aux1, gLnk("WTL::CPaneContainer", "", "classWTL_1_1CPaneContainer.html"))
       insDoc(aux1, gLnk("WTL::CPaneContainerImpl", "", "classWTL_1_1CPaneContainerImpl.html"))
       insDoc(aux1, gLnk("WTL::CPenT", "", "classWTL_1_1CPenT.html"))
       insDoc(aux1, gLnk("WTL::CPoint", "", "classWTL_1_1CPoint.html"))
       insDoc(aux1, gLnk("WTL::CPrintDialog", "", "classWTL_1_1CPrintDialog.html"))
       insDoc(aux1, gLnk("WTL::CPrintDialogEx", "", "classWTL_1_1CPrintDialogEx.html"))
       insDoc(aux1, gLnk("WTL::CPrintDialogExImpl", "", "classWTL_1_1CPrintDialogExImpl.html"))
       insDoc(aux1, gLnk("WTL::CPrintDialogImpl", "", "classWTL_1_1CPrintDialogImpl.html"))
       insDoc(aux1, gLnk("WTL::CPrinterDC", "", "classWTL_1_1CPrinterDC.html"))
       insDoc(aux1, gLnk("WTL::CPrinterInfo", "", "classWTL_1_1CPrinterInfo.html"))
       insDoc(aux1, gLnk("WTL::CPrinterT", "", "classWTL_1_1CPrinterT.html"))
       insDoc(aux1, gLnk("WTL::CPrintJob", "", "classWTL_1_1CPrintJob.html"))
       insDoc(aux1, gLnk("WTL::CPrintJobInfo", "", "classWTL_1_1CPrintJobInfo.html"))
       insDoc(aux1, gLnk("WTL::CPrintPreview", "", "classWTL_1_1CPrintPreview.html"))
       insDoc(aux1, gLnk("WTL::CPrintPreviewWindow", "", "classWTL_1_1CPrintPreviewWindow.html"))
       insDoc(aux1, gLnk("WTL::CPrintPreviewWindowImpl", "", "classWTL_1_1CPrintPreviewWindowImpl.html"))
       insDoc(aux1, gLnk("WTL::CProgressBarCtrlT", "", "classWTL_1_1CProgressBarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CPropertyPage", "", "classWTL_1_1CPropertyPage.html"))
       insDoc(aux1, gLnk("WTL::CPropertyPageImpl", "", "classWTL_1_1CPropertyPageImpl.html"))
       insDoc(aux1, gLnk("WTL::CPropertyPageWindow", "", "classWTL_1_1CPropertyPageWindow.html"))
       insDoc(aux1, gLnk("WTL::CPropertySheet", "", "classWTL_1_1CPropertySheet.html"))
       insDoc(aux1, gLnk("WTL::CPropertySheetImpl", "", "classWTL_1_1CPropertySheetImpl.html"))
       insDoc(aux1, gLnk("WTL::CPropertySheetWindow", "", "classWTL_1_1CPropertySheetWindow.html"))
       insDoc(aux1, gLnk("WTL::CReBarCtrlT", "", "classWTL_1_1CReBarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CRecentDocumentList", "", "classWTL_1_1CRecentDocumentList.html"))
       insDoc(aux1, gLnk("WTL::CRecentDocumentListBase", "", "classWTL_1_1CRecentDocumentListBase.html"))
       insDoc(aux1, gLnk("WTL::CRecentDocumentListBase::_DocEntry", "", "structWTL_1_1CRecentDocumentListBase_1_1__DocEntry.html"))
       insDoc(aux1, gLnk("WTL::CRect", "", "classWTL_1_1CRect.html"))
       insDoc(aux1, gLnk("WTL::CRgnT", "", "classWTL_1_1CRgnT.html"))
       insDoc(aux1, gLnk("WTL::CRichEditCommands", "", "classWTL_1_1CRichEditCommands.html"))
       insDoc(aux1, gLnk("WTL::CRichEditCtrlT", "", "classWTL_1_1CRichEditCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CScrollBarT", "", "classWTL_1_1CScrollBarT.html"))
       insDoc(aux1, gLnk("WTL::CScrollImpl", "", "classWTL_1_1CScrollImpl.html"))
       insDoc(aux1, gLnk("WTL::CScrollWindowImpl", "", "classWTL_1_1CScrollWindowImpl.html"))
       insDoc(aux1, gLnk("WTL::CServerAppModule", "", "classWTL_1_1CServerAppModule.html"))
       insDoc(aux1, gLnk("CSimpleArray", "", "classCSimpleArray.html"))
       insDoc(aux1, gLnk("WTL::CSimpleStack", "", "classWTL_1_1CSimpleStack.html"))
       insDoc(aux1, gLnk("WTL::CSize", "", "classWTL_1_1CSize.html"))
       insDoc(aux1, gLnk("WTL::CSplitterImpl", "", "classWTL_1_1CSplitterImpl.html"))
       insDoc(aux1, gLnk("WTL::CSplitterWindowImpl", "", "classWTL_1_1CSplitterWindowImpl.html"))
       insDoc(aux1, gLnk("WTL::CSplitterWindowT", "", "classWTL_1_1CSplitterWindowT.html"))
       insDoc(aux1, gLnk("WTL::CStaticT", "", "classWTL_1_1CStaticT.html"))
       insDoc(aux1, gLnk("WTL::CStatusBarCtrlT", "", "classWTL_1_1CStatusBarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CString", "", "classWTL_1_1CString.html"))
       insDoc(aux1, gLnk("WTL::CStringData", "", "structWTL_1_1CStringData.html"))
       insDoc(aux1, gLnk("WTL::CTabCtrlT", "", "classWTL_1_1CTabCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CTheme", "", "classWTL_1_1CTheme.html"))
       insDoc(aux1, gLnk("WTL::CThemeImpl", "", "classWTL_1_1CThemeImpl.html"))
       insDoc(aux1, gLnk("WTL::CToolBarCtrlT", "", "classWTL_1_1CToolBarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CToolInfo", "", "classWTL_1_1CToolInfo.html"))
       insDoc(aux1, gLnk("WTL::CToolTipCtrlT", "", "classWTL_1_1CToolTipCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CTrackBarCtrlT", "", "classWTL_1_1CTrackBarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CTreeItem", "", "classWTL_1_1CTreeItem.html"))
       insDoc(aux1, gLnk("WTL::CTreeViewCtrlExT", "", "classWTL_1_1CTreeViewCtrlExT.html"))
       insDoc(aux1, gLnk("WTL::CTreeViewCtrlT", "", "classWTL_1_1CTreeViewCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CUpdateUI", "", "classWTL_1_1CUpdateUI.html"))
       insDoc(aux1, gLnk("WTL::CUpdateUIBase", "", "classWTL_1_1CUpdateUIBase.html"))
       insDoc(aux1, gLnk("WTL::CUpdateUIBase::_AtlUpdateUIData", "", "structWTL_1_1CUpdateUIBase_1_1__AtlUpdateUIData.html"))
       insDoc(aux1, gLnk("WTL::CUpdateUIBase::_AtlUpdateUIElement", "", "structWTL_1_1CUpdateUIBase_1_1__AtlUpdateUIElement.html"))
       insDoc(aux1, gLnk("WTL::CUpdateUIBase::_AtlUpdateUIMap", "", "structWTL_1_1CUpdateUIBase_1_1__AtlUpdateUIMap.html"))
       insDoc(aux1, gLnk("WTL::CUpDownCtrlT", "", "classWTL_1_1CUpDownCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CWaitCursor", "", "classWTL_1_1CWaitCursor.html"))
       insDoc(aux1, gLnk("WTL::CWinDataExchange", "", "classWTL_1_1CWinDataExchange.html"))
       insDoc(aux1, gLnk("WTL::CWinDataExchange::_XData", "", "structWTL_1_1CWinDataExchange_1_1__XData.html"))
       insDoc(aux1, gLnk("WTL::CWinDataExchange::_XFloatData", "", "structWTL_1_1CWinDataExchange_1_1__XFloatData.html"))
       insDoc(aux1, gLnk("WTL::CWinDataExchange::_XIntData", "", "structWTL_1_1CWinDataExchange_1_1__XIntData.html"))
       insDoc(aux1, gLnk("WTL::CWinDataExchange::_XTextData", "", "structWTL_1_1CWinDataExchange_1_1__XTextData.html"))
       insDoc(aux1, gLnk("CWindow", "", "classCWindow.html"))
       insDoc(aux1, gLnk("WTL::CWindowDC", "", "classWTL_1_1CWindowDC.html"))
       insDoc(aux1, gLnk("CWindowImpl", "", "classCWindowImpl.html"))
       insDoc(aux1, gLnk("CWindowImplBaseT", "", "classCWindowImplBaseT.html"))
       insDoc(aux1, gLnk("IObjectWithSiteImpl", "", "classIObjectWithSiteImpl.html"))
       insDoc(aux1, gLnk("IPrintDialogCallback", "", "classIPrintDialogCallback.html"))
       insDoc(aux1, gLnk("WTL::IPrintJobInfo", "", "classWTL_1_1IPrintJobInfo.html"))
       insDoc(aux1, gLnk("WTL::tagCBRPOPUPMENU", "", "structWTL_1_1tagCBRPOPUPMENU.html"))
aux1 = insFld(foldersTree, gFld("Class Hierarchy", "", "hierarchy.html"))
       insDoc(aux1, gLnk("WTL::_AtlFrameWnd_CmdBarPopupMenu", "", "structWTL_1_1__AtlFrameWnd__CmdBarPopupMenu.html"))
       insDoc(aux1, gLnk("WTL::_printer_info", "", "classWTL_1_1__printer__info.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 1 >", "", "classWTL_1_1__printer__info_3_011_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 2 >", "", "classWTL_1_1__printer__info_3_012_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 3 >", "", "classWTL_1_1__printer__info_3_013_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 4 >", "", "classWTL_1_1__printer__info_3_014_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 5 >", "", "classWTL_1_1__printer__info_3_015_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 6 >", "", "classWTL_1_1__printer__info_3_016_01_4.html"))
       insDoc(aux1, gLnk("WTL::_printer_info< 7 >", "", "classWTL_1_1__printer__info_3_017_01_4.html"))
       insDoc(aux1, gLnk("WTL::_U_MENUorID", "", "classWTL_1_1__U__MENUorID.html"))
       insDoc(aux1, gLnk("WTL::_U_RECT", "", "classWTL_1_1__U__RECT.html"))
       insDoc(aux1, gLnk("WTL::_U_STRINGorID", "", "classWTL_1_1__U__STRINGorID.html"))
       insDoc(aux1, gLnk("WTL::CAnimateCtrlT", "", "classWTL_1_1CAnimateCtrlT.html"))
  aux2 = insFld(aux1, gFld("WTL::CAppModule", "", "classWTL_1_1CAppModule.html"))
         insDoc(aux2, gLnk("WTL::CServerAppModule", "", "classWTL_1_1CServerAppModule.html"))
       insDoc(aux1, gLnk("WTL::CAppModule::_ATL_EMPTY_DLGTEMPLATE", "", "structWTL_1_1CAppModule_1_1__ATL__EMPTY__DLGTEMPLATE.html"))
       insDoc(aux1, gLnk("WTL::CBitmapT", "", "classWTL_1_1CBitmapT.html"))
       insDoc(aux1, gLnk("WTL::CBrushT", "", "classWTL_1_1CBrushT.html"))
       insDoc(aux1, gLnk("WTL::CButtonT", "", "classWTL_1_1CButtonT.html"))
       insDoc(aux1, gLnk("WTL::CCheckListViewCtrlImplTraits", "", "classWTL_1_1CCheckListViewCtrlImplTraits.html"))
  aux2 = insFld(aux1, gFld("WTL::CComboBoxT", "", "classWTL_1_1CComboBoxT.html"))
         insDoc(aux2, gLnk("WTL::CComboBoxExT", "", "classWTL_1_1CComboBoxExT.html"))
       insDoc(aux1, gLnk("WTL::CCommandBarCtrlBase::_MsgHookData", "", "structWTL_1_1CCommandBarCtrlBase_1_1__MsgHookData.html"))
  aux2 = insFld(aux1, gFld("CCommandBarCtrlImpl", "", "classCCommandBarCtrlImpl.html"))
         insDoc(aux2, gLnk("WTL::CCommandBarCtrl", "", "classWTL_1_1CCommandBarCtrl.html"))
         insDoc(aux2, gLnk("WTL::CMDICommandBarCtrlImpl", "", "classWTL_1_1CMDICommandBarCtrlImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CMDICommandBarCtrlImpl< CMDICommandBarCtrl >", "", "classWTL_1_1CMDICommandBarCtrlImpl.html"))
           insDoc(aux3, gLnk("WTL::CMDICommandBarCtrl", "", "classWTL_1_1CMDICommandBarCtrl.html"))
  aux2 = insFld(aux1, gFld("WTL::CCommonDialogImplBase", "", "classWTL_1_1CCommonDialogImplBase.html"))
         insDoc(aux2, gLnk("WTL::CColorDialogImpl", "", "classWTL_1_1CColorDialogImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CColorDialogImpl< CColorDialog >", "", "classWTL_1_1CColorDialogImpl.html"))
           insDoc(aux3, gLnk("WTL::CColorDialog", "", "classWTL_1_1CColorDialog.html"))
         insDoc(aux2, gLnk("WTL::CFindReplaceDialogImpl", "", "classWTL_1_1CFindReplaceDialogImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CFindReplaceDialogImpl< CFindReplaceDialog >", "", "classWTL_1_1CFindReplaceDialogImpl.html"))
           insDoc(aux3, gLnk("WTL::CFindReplaceDialog", "", "classWTL_1_1CFindReplaceDialog.html"))
         insDoc(aux2, gLnk("WTL::CFontDialogImpl", "", "classWTL_1_1CFontDialogImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CFontDialogImpl< CFontDialog >", "", "classWTL_1_1CFontDialogImpl.html"))
           insDoc(aux3, gLnk("WTL::CFontDialog", "", "classWTL_1_1CFontDialog.html"))
         insDoc(aux2, gLnk("WTL::CPageSetupDialogImpl", "", "classWTL_1_1CPageSetupDialogImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CPageSetupDialogImpl< CPageSetupDialog >", "", "classWTL_1_1CPageSetupDialogImpl.html"))
           insDoc(aux3, gLnk("WTL::CPageSetupDialog", "", "classWTL_1_1CPageSetupDialog.html"))
         insDoc(aux2, gLnk("WTL::CPrintDialogImpl", "", "classWTL_1_1CPrintDialogImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CPrintDialogImpl< CPrintDialog >", "", "classWTL_1_1CPrintDialogImpl.html"))
           insDoc(aux3, gLnk("WTL::CPrintDialog", "", "classWTL_1_1CPrintDialog.html"))
  aux2 = insFld(aux1, gFld("WTL::CCustomDraw", "", "classWTL_1_1CCustomDraw.html"))
         insDoc(aux2, gLnk("WTL::CPaneContainerImpl", "", "classWTL_1_1CPaneContainerImpl.html"))
  aux2 = insFld(aux1, gFld("WTL::CCustomDraw< CPaneContainer >", "", "classWTL_1_1CCustomDraw.html"))
    aux3 = insFld(aux2, gFld("WTL::CPaneContainerImpl< CPaneContainer >", "", "classWTL_1_1CPaneContainerImpl.html"))
           insDoc(aux3, gLnk("WTL::CPaneContainer", "", "classWTL_1_1CPaneContainer.html"))
       insDoc(aux1, gLnk("WTL::CDateTimePickerCtrlT", "", "classWTL_1_1CDateTimePickerCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CDCT", "", "classWTL_1_1CDCT.html"))
  aux2 = insFld(aux1, gFld("WTL::CDCT< true >", "", "classWTL_1_1CDCT.html"))
         insDoc(aux2, gLnk("WTL::CClientDC", "", "classWTL_1_1CClientDC.html"))
         insDoc(aux2, gLnk("WTL::CEnhMetaFileDC", "", "classWTL_1_1CEnhMetaFileDC.html"))
         insDoc(aux2, gLnk("WTL::CPaintDC", "", "classWTL_1_1CPaintDC.html"))
         insDoc(aux2, gLnk("WTL::CPrinterDC", "", "classWTL_1_1CPrinterDC.html"))
         insDoc(aux2, gLnk("WTL::CWindowDC", "", "classWTL_1_1CWindowDC.html"))
       insDoc(aux1, gLnk("WTL::CDevModeT", "", "classWTL_1_1CDevModeT.html"))
  aux2 = insFld(aux1, gFld("CDialogImplBase", "", "classCDialogImplBase.html"))
         insDoc(aux2, gLnk("WTL::CFileDialogImpl", "", "classWTL_1_1CFileDialogImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CFileDialogImpl< CFileDialog >", "", "classWTL_1_1CFileDialogImpl.html"))
           insDoc(aux3, gLnk("WTL::CFileDialog", "", "classWTL_1_1CFileDialog.html"))
  aux2 = insFld(aux1, gFld("CDialogImplBaseT", "", "classCDialogImplBaseT.html"))
    aux3 = insFld(aux2, gFld("WTL::CPropertyPageImpl", "", "classWTL_1_1CPropertyPageImpl.html"))
           insDoc(aux3, gLnk("WTL::CAxPropertyPageImpl", "", "classWTL_1_1CAxPropertyPageImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CPropertyPageImpl< CAxPropertyPage< t_wDlgTemplateID >, CPropertyPageWindow >", "", "classWTL_1_1CPropertyPageImpl.html"))
      aux4 = insFld(aux3, gFld("WTL::CAxPropertyPageImpl< CAxPropertyPage< t_wDlgTemplateID > >", "", "classWTL_1_1CAxPropertyPageImpl.html"))
             insDoc(aux4, gLnk("WTL::CAxPropertyPage", "", "classWTL_1_1CAxPropertyPage.html"))
    aux3 = insFld(aux2, gFld("WTL::CPropertyPageImpl< CPropertyPage< t_wDlgTemplateID > >", "", "classWTL_1_1CPropertyPageImpl.html"))
           insDoc(aux3, gLnk("WTL::CPropertyPage", "", "classWTL_1_1CPropertyPage.html"))
       insDoc(aux1, gLnk("WTL::CDialogResize", "", "classWTL_1_1CDialogResize.html"))
       insDoc(aux1, gLnk("WTL::CDialogResize::_AtlDlgResizeData", "", "structWTL_1_1CDialogResize_1_1__AtlDlgResizeData.html"))
       insDoc(aux1, gLnk("WTL::CDialogResize::_AtlDlgResizeMap", "", "structWTL_1_1CDialogResize_1_1__AtlDlgResizeMap.html"))
       insDoc(aux1, gLnk("WTL::CDragListNotifyImpl", "", "classWTL_1_1CDragListNotifyImpl.html"))
  aux2 = insFld(aux1, gFld("WTL::CEditCommands", "", "classWTL_1_1CEditCommands.html"))
         insDoc(aux2, gLnk("WTL::CRichEditCommands", "", "classWTL_1_1CRichEditCommands.html"))
       insDoc(aux1, gLnk("WTL::CEditT", "", "classWTL_1_1CEditT.html"))
       insDoc(aux1, gLnk("WTL::CEnhMetaFileInfo", "", "classWTL_1_1CEnhMetaFileInfo.html"))
       insDoc(aux1, gLnk("WTL::CEnhMetaFileT", "", "classWTL_1_1CEnhMetaFileT.html"))
       insDoc(aux1, gLnk("WTL::CFindFile", "", "classWTL_1_1CFindFile.html"))
       insDoc(aux1, gLnk("WTL::CFlatScrollBarImpl", "", "classWTL_1_1CFlatScrollBarImpl.html"))
  aux2 = insFld(aux1, gFld("WTL::CFlatScrollBarImpl< CFlatScrollBarT< TBase > >", "", "classWTL_1_1CFlatScrollBarImpl.html"))
         insDoc(aux2, gLnk("WTL::CFlatScrollBarT", "", "classWTL_1_1CFlatScrollBarT.html"))
       insDoc(aux1, gLnk("WTL::CFolderDialogImpl", "", "classWTL_1_1CFolderDialogImpl.html"))
  aux2 = insFld(aux1, gFld("WTL::CFolderDialogImpl< CFolderDialog >", "", "classWTL_1_1CFolderDialogImpl.html"))
         insDoc(aux2, gLnk("WTL::CFolderDialog", "", "classWTL_1_1CFolderDialog.html"))
       insDoc(aux1, gLnk("WTL::CFontT", "", "classWTL_1_1CFontT.html"))
       insDoc(aux1, gLnk("WTL::CFrameWindowImplBase::_AtlToolBarData", "", "structWTL_1_1CFrameWindowImplBase_1_1__AtlToolBarData.html"))
       insDoc(aux1, gLnk("WTL::CFrameWindowImplBase::_ChevronMenuInfo", "", "structWTL_1_1CFrameWindowImplBase_1_1__ChevronMenuInfo.html"))
       insDoc(aux1, gLnk("WTL::CFrameWndClassInfo", "", "classWTL_1_1CFrameWndClassInfo.html"))
       insDoc(aux1, gLnk("WTL::CHeaderCtrlT", "", "classWTL_1_1CHeaderCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CHotKeyCtrlT", "", "classWTL_1_1CHotKeyCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CIdleHandler", "", "classWTL_1_1CIdleHandler.html"))
       insDoc(aux1, gLnk("WTL::CImageList", "", "classWTL_1_1CImageList.html"))
       insDoc(aux1, gLnk("WTL::CIPAddressCtrlT", "", "classWTL_1_1CIPAddressCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CLinkCtrlT", "", "classWTL_1_1CLinkCtrlT.html"))
  aux2 = insFld(aux1, gFld("WTL::CListBoxT", "", "classWTL_1_1CListBoxT.html"))
         insDoc(aux2, gLnk("WTL::CDragListBoxT", "", "classWTL_1_1CDragListBoxT.html"))
       insDoc(aux1, gLnk("WTL::CListViewCtrlT", "", "classWTL_1_1CListViewCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CMenuItemInfo", "", "classWTL_1_1CMenuItemInfo.html"))
       insDoc(aux1, gLnk("WTL::CMenuT", "", "classWTL_1_1CMenuT.html"))
       insDoc(aux1, gLnk("WTL::CMessageFilter", "", "classWTL_1_1CMessageFilter.html"))
       insDoc(aux1, gLnk("WTL::CMessageLoop", "", "classWTL_1_1CMessageLoop.html"))
  aux2 = insFld(aux1, gFld("CMessageMap", "", "classCMessageMap.html"))
         insDoc(aux2, gLnk("WTL::CPrintDialogExImpl", "", "classWTL_1_1CPrintDialogExImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CPrintDialogExImpl< CPrintDialogEx >", "", "classWTL_1_1CPrintDialogExImpl.html"))
           insDoc(aux3, gLnk("WTL::CPrintDialogEx", "", "classWTL_1_1CPrintDialogEx.html"))
       insDoc(aux1, gLnk("WTL::CMonthCalendarCtrlT", "", "classWTL_1_1CMonthCalendarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::COwnerDraw", "", "classWTL_1_1COwnerDraw.html"))
       insDoc(aux1, gLnk("WTL::CPagerCtrlT", "", "classWTL_1_1CPagerCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CPaletteT", "", "classWTL_1_1CPaletteT.html"))
       insDoc(aux1, gLnk("WTL::CPenT", "", "classWTL_1_1CPenT.html"))
       insDoc(aux1, gLnk("WTL::CPoint", "", "classWTL_1_1CPoint.html"))
       insDoc(aux1, gLnk("WTL::CPrinterInfo", "", "classWTL_1_1CPrinterInfo.html"))
       insDoc(aux1, gLnk("WTL::CPrinterT", "", "classWTL_1_1CPrinterT.html"))
       insDoc(aux1, gLnk("WTL::CPrintJob", "", "classWTL_1_1CPrintJob.html"))
  aux2 = insFld(aux1, gFld("WTL::CPrintPreview", "", "classWTL_1_1CPrintPreview.html"))
         insDoc(aux2, gLnk("WTL::CPrintPreviewWindowImpl", "", "classWTL_1_1CPrintPreviewWindowImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CPrintPreviewWindowImpl< CPrintPreviewWindow >", "", "classWTL_1_1CPrintPreviewWindowImpl.html"))
           insDoc(aux3, gLnk("WTL::CPrintPreviewWindow", "", "classWTL_1_1CPrintPreviewWindow.html"))
       insDoc(aux1, gLnk("WTL::CProgressBarCtrlT", "", "classWTL_1_1CProgressBarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CReBarCtrlT", "", "classWTL_1_1CReBarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CRecentDocumentListBase", "", "classWTL_1_1CRecentDocumentListBase.html"))
       insDoc(aux1, gLnk("WTL::CRecentDocumentListBase::_DocEntry", "", "structWTL_1_1CRecentDocumentListBase_1_1__DocEntry.html"))
  aux2 = insFld(aux1, gFld("WTL::CRecentDocumentListBase< CRecentDocumentList >", "", "classWTL_1_1CRecentDocumentListBase.html"))
         insDoc(aux2, gLnk("WTL::CRecentDocumentList", "", "classWTL_1_1CRecentDocumentList.html"))
       insDoc(aux1, gLnk("WTL::CRect", "", "classWTL_1_1CRect.html"))
       insDoc(aux1, gLnk("WTL::CRgnT", "", "classWTL_1_1CRgnT.html"))
       insDoc(aux1, gLnk("WTL::CRichEditCtrlT", "", "classWTL_1_1CRichEditCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CScrollBarT", "", "classWTL_1_1CScrollBarT.html"))
  aux2 = insFld(aux1, gFld("WTL::CScrollImpl", "", "classWTL_1_1CScrollImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CMapScrollImpl", "", "classWTL_1_1CMapScrollImpl.html"))
           insDoc(aux3, gLnk("WTL::CMapScrollWindowImpl", "", "classWTL_1_1CMapScrollWindowImpl.html"))
         insDoc(aux2, gLnk("WTL::CScrollWindowImpl", "", "classWTL_1_1CScrollWindowImpl.html"))
  aux2 = insFld(aux1, gFld("CSimpleArray", "", "classCSimpleArray.html"))
         insDoc(aux2, gLnk("WTL::CSimpleStack", "", "classWTL_1_1CSimpleStack.html"))
       insDoc(aux1, gLnk("WTL::CSize", "", "classWTL_1_1CSize.html"))
  aux2 = insFld(aux1, gFld("WTL::CSplitterImpl", "", "classWTL_1_1CSplitterImpl.html"))
         insDoc(aux2, gLnk("WTL::CSplitterWindowImpl", "", "classWTL_1_1CSplitterWindowImpl.html"))
  aux2 = insFld(aux1, gFld("WTL::CSplitterImpl< CSplitterWindowT< t_bVertical >, t_bVertical >", "", "classWTL_1_1CSplitterImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CSplitterWindowImpl< CSplitterWindowT< t_bVertical >, t_bVertical >", "", "classWTL_1_1CSplitterWindowImpl.html"))
           insDoc(aux3, gLnk("WTL::CSplitterWindowT", "", "classWTL_1_1CSplitterWindowT.html"))
       insDoc(aux1, gLnk("WTL::CStaticT", "", "classWTL_1_1CStaticT.html"))
       insDoc(aux1, gLnk("WTL::CStatusBarCtrlT", "", "classWTL_1_1CStatusBarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CString", "", "classWTL_1_1CString.html"))
       insDoc(aux1, gLnk("WTL::CStringData", "", "structWTL_1_1CStringData.html"))
       insDoc(aux1, gLnk("WTL::CTabCtrlT", "", "classWTL_1_1CTabCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CTheme", "", "classWTL_1_1CTheme.html"))
       insDoc(aux1, gLnk("WTL::CThemeImpl", "", "classWTL_1_1CThemeImpl.html"))
       insDoc(aux1, gLnk("WTL::CToolBarCtrlT", "", "classWTL_1_1CToolBarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CToolInfo", "", "classWTL_1_1CToolInfo.html"))
       insDoc(aux1, gLnk("WTL::CToolTipCtrlT", "", "classWTL_1_1CToolTipCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CTrackBarCtrlT", "", "classWTL_1_1CTrackBarCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CTreeItem", "", "classWTL_1_1CTreeItem.html"))
  aux2 = insFld(aux1, gFld("WTL::CTreeViewCtrlT", "", "classWTL_1_1CTreeViewCtrlT.html"))
         insDoc(aux2, gLnk("WTL::CTreeViewCtrlExT", "", "classWTL_1_1CTreeViewCtrlExT.html"))
  aux2 = insFld(aux1, gFld("WTL::CUpdateUIBase", "", "classWTL_1_1CUpdateUIBase.html"))
         insDoc(aux2, gLnk("WTL::CUpdateUI", "", "classWTL_1_1CUpdateUI.html"))
       insDoc(aux1, gLnk("WTL::CUpdateUIBase::_AtlUpdateUIData", "", "structWTL_1_1CUpdateUIBase_1_1__AtlUpdateUIData.html"))
       insDoc(aux1, gLnk("WTL::CUpdateUIBase::_AtlUpdateUIElement", "", "structWTL_1_1CUpdateUIBase_1_1__AtlUpdateUIElement.html"))
       insDoc(aux1, gLnk("WTL::CUpdateUIBase::_AtlUpdateUIMap", "", "structWTL_1_1CUpdateUIBase_1_1__AtlUpdateUIMap.html"))
       insDoc(aux1, gLnk("WTL::CUpDownCtrlT", "", "classWTL_1_1CUpDownCtrlT.html"))
       insDoc(aux1, gLnk("WTL::CWaitCursor", "", "classWTL_1_1CWaitCursor.html"))
       insDoc(aux1, gLnk("WTL::CWinDataExchange", "", "classWTL_1_1CWinDataExchange.html"))
       insDoc(aux1, gLnk("WTL::CWinDataExchange::_XData", "", "structWTL_1_1CWinDataExchange_1_1__XData.html"))
       insDoc(aux1, gLnk("WTL::CWinDataExchange::_XFloatData", "", "structWTL_1_1CWinDataExchange_1_1__XFloatData.html"))
       insDoc(aux1, gLnk("WTL::CWinDataExchange::_XIntData", "", "structWTL_1_1CWinDataExchange_1_1__XIntData.html"))
       insDoc(aux1, gLnk("WTL::CWinDataExchange::_XTextData", "", "structWTL_1_1CWinDataExchange_1_1__XTextData.html"))
  aux2 = insFld(aux1, gFld("CWindow", "", "classCWindow.html"))
         insDoc(aux2, gLnk("WTL::CMDIWindow", "", "classWTL_1_1CMDIWindow.html"))
         insDoc(aux2, gLnk("WTL::CPrintDialogExImpl", "", "classWTL_1_1CPrintDialogExImpl.html"))
         insDoc(aux2, gLnk("WTL::CPrintDialogExImpl< CPrintDialogEx >", "", "classWTL_1_1CPrintDialogExImpl.html"))
         insDoc(aux2, gLnk("WTL::CPropertyPageWindow", "", "classWTL_1_1CPropertyPageWindow.html"))
         insDoc(aux2, gLnk("WTL::CPropertySheetWindow", "", "classWTL_1_1CPropertySheetWindow.html"))
    aux3 = insFld(aux2, gFld("WTL::CToolBarCtrlT< CWindow >", "", "classWTL_1_1CToolBarCtrlT.html"))
           insDoc(aux3, gLnk("WTL::CCommandBarCtrlBase", "", "classWTL_1_1CCommandBarCtrlBase.html"))
         insDoc(aux2, gLnk("WTL::CToolTipCtrlT< CWindow >", "", "classWTL_1_1CToolTipCtrlT.html"))
  aux2 = insFld(aux1, gFld("CWindowImpl", "", "classCWindowImpl.html"))
         insDoc(aux2, gLnk("WTL::CBitmapButtonImpl", "", "classWTL_1_1CBitmapButtonImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CBitmapButtonImpl< CBitmapButton >", "", "classWTL_1_1CBitmapButtonImpl.html"))
           insDoc(aux3, gLnk("WTL::CBitmapButton", "", "classWTL_1_1CBitmapButton.html"))
         insDoc(aux2, gLnk("WTL::CCheckListViewCtrlImpl", "", "classWTL_1_1CCheckListViewCtrlImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CCheckListViewCtrlImpl< CCheckListViewCtrl >", "", "classWTL_1_1CCheckListViewCtrlImpl.html"))
           insDoc(aux3, gLnk("WTL::CCheckListViewCtrl", "", "classWTL_1_1CCheckListViewCtrl.html"))
         insDoc(aux2, gLnk("WTL::CHyperLinkImpl", "", "classWTL_1_1CHyperLinkImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CHyperLinkImpl< CHyperLink >", "", "classWTL_1_1CHyperLinkImpl.html"))
           insDoc(aux3, gLnk("WTL::CHyperLink", "", "classWTL_1_1CHyperLink.html"))
         insDoc(aux2, gLnk("WTL::CMapScrollWindowImpl", "", "classWTL_1_1CMapScrollWindowImpl.html"))
         insDoc(aux2, gLnk("WTL::CMultiPaneStatusBarCtrlImpl", "", "classWTL_1_1CMultiPaneStatusBarCtrlImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CMultiPaneStatusBarCtrlImpl< CMultiPaneStatusBarCtrl >", "", "classWTL_1_1CMultiPaneStatusBarCtrlImpl.html"))
           insDoc(aux3, gLnk("WTL::CMultiPaneStatusBarCtrl", "", "classWTL_1_1CMultiPaneStatusBarCtrl.html"))
         insDoc(aux2, gLnk("WTL::CPaneContainerImpl", "", "classWTL_1_1CPaneContainerImpl.html"))
         insDoc(aux2, gLnk("WTL::CPaneContainerImpl< CPaneContainer >", "", "classWTL_1_1CPaneContainerImpl.html"))
         insDoc(aux2, gLnk("WTL::CPrintPreviewWindowImpl", "", "classWTL_1_1CPrintPreviewWindowImpl.html"))
         insDoc(aux2, gLnk("WTL::CPrintPreviewWindowImpl< CPrintPreviewWindow >", "", "classWTL_1_1CPrintPreviewWindowImpl.html"))
         insDoc(aux2, gLnk("WTL::CScrollWindowImpl", "", "classWTL_1_1CScrollWindowImpl.html"))
         insDoc(aux2, gLnk("WTL::CSplitterWindowImpl", "", "classWTL_1_1CSplitterWindowImpl.html"))
         insDoc(aux2, gLnk("WTL::CSplitterWindowImpl< CSplitterWindowT< t_bVertical >, t_bVertical >", "", "classWTL_1_1CSplitterWindowImpl.html"))
  aux2 = insFld(aux1, gFld("CWindowImplBaseT", "", "classCWindowImplBaseT.html"))
    aux3 = insFld(aux2, gFld("WTL::CFrameWindowImplBase", "", "classWTL_1_1CFrameWindowImplBase.html"))
           insDoc(aux3, gLnk("WTL::CFrameWindowImpl", "", "classWTL_1_1CFrameWindowImpl.html"))
           insDoc(aux3, gLnk("WTL::CMDIChildWindowImpl", "", "classWTL_1_1CMDIChildWindowImpl.html"))
           insDoc(aux3, gLnk("WTL::CMDIFrameWindowImpl", "", "classWTL_1_1CMDIFrameWindowImpl.html"))
         insDoc(aux2, gLnk("WTL::CPropertySheetImpl", "", "classWTL_1_1CPropertySheetImpl.html"))
    aux3 = insFld(aux2, gFld("WTL::CPropertySheetImpl< CPropertySheet >", "", "classWTL_1_1CPropertySheetImpl.html"))
           insDoc(aux3, gLnk("WTL::CPropertySheet", "", "classWTL_1_1CPropertySheet.html"))
  aux2 = insFld(aux1, gFld("IObjectWithSiteImpl", "", "classIObjectWithSiteImpl.html"))
         insDoc(aux2, gLnk("WTL::CPrintDialogExImpl", "", "classWTL_1_1CPrintDialogExImpl.html"))
         insDoc(aux2, gLnk("WTL::CPrintDialogExImpl< CPrintDialogEx >", "", "classWTL_1_1CPrintDialogExImpl.html"))
  aux2 = insFld(aux1, gFld("IPrintDialogCallback", "", "classIPrintDialogCallback.html"))
         insDoc(aux2, gLnk("WTL::CPrintDialogExImpl", "", "classWTL_1_1CPrintDialogExImpl.html"))
         insDoc(aux2, gLnk("WTL::CPrintDialogExImpl< CPrintDialogEx >", "", "classWTL_1_1CPrintDialogExImpl.html"))
  aux2 = insFld(aux1, gFld("WTL::IPrintJobInfo", "", "classWTL_1_1IPrintJobInfo.html"))
         insDoc(aux2, gLnk("WTL::CPrintJobInfo", "", "classWTL_1_1CPrintJobInfo.html"))
       insDoc(aux1, gLnk("WTL::tagCBRPOPUPMENU", "", "structWTL_1_1tagCBRPOPUPMENU.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Namespace List", "", "namespaces.html"))
       insDoc(aux1, gLnk("WTL", "", "namespaceWTL.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
     insDoc(foldersTree, gLnk("Namespace Members", "", "namespacemembers.html"))
